import type { CapabilityCard, CapabilityStatus, CompositionGrammar, DesignerMotif, FunctionalModule, SpatialAtomDefinition } from "./schema";

const atom = (value: Omit<SpatialAtomDefinition, "version" | "parameters" | "footprintCells" | "elevationFeet" | "ports" | "inputPorts" | "outputPorts" | "supportSurfaces" | "walkableSurfaces" | "blockedVolumes" | "clearanceVolumes" | "traversal" | "adjacencyConditions" | "placementConstraints" | "constraints" | "tacticalEffects" | "gridRule" | "lod" | "instancingStrategy" | "performanceBudget" | "validation" | "visualFixtures" | "failureConditions"> & Partial<SpatialAtomDefinition>): SpatialAtomDefinition => ({
  version: 1,
  parameters: [], footprintCells: { min: [1, 1], max: [64, 64] }, elevationFeet: { min: -100, max: 300 }, ports: [], inputPorts: [], outputPorts: [], supportSurfaces: [], walkableSurfaces: [], blockedVolumes: [], clearanceVolumes: [], traversal: ["walk"], adjacencyConditions: [], placementConstraints: [], constraints: [], tacticalEffects: [], gridRule: "surface", lod: "batched", instancingStrategy: "merged-batch", performanceBudget: { maxTriangles: 12000, maxDrawCalls: 2 }, validation: ["finite-geometry", "surface-grid-aligned"], visualFixtures: ["small-sparse", "medium-balanced", "large-dense", "same-seed-replay", "different-seed-variation"], failureConditions: ["zero-height", "floating-without-support"],
  ...value,
});

export const GEOMETRY_PRIMITIVES = [
  { id: "primitive.box", status: "production-ready", description: "板、梁、墙和地形单元。", builder: "box", supportsGrid: true, supportsBatching: true },
  { id: "primitive.cylinder", status: "production-ready", description: "柱、树干、圆台与池体。", builder: "cylinder", supportsGrid: true, supportsBatching: true },
  { id: "primitive.path-band", status: "production-ready", description: "道路、桥面、水道和曲线路径带。", builder: "corridor", supportsGrid: true, supportsBatching: true },
  { id: "primitive.stair-run", status: "production-ready", description: "带端点合同的连续台阶。", builder: "stairConnection", supportsGrid: true, supportsBatching: false },
  { id: "primitive.gable", status: "production-ready", description: "真实三角截面坡屋顶。", builder: "gable", supportsGrid: false, supportsBatching: true },
  { id: "primitive.ramp", status: "production-ready", description: "可旋转、可批处理的三角楔形坡面外观。", builder: "ramp", supportsGrid: false, supportsBatching: true },
  { id: "primitive.water-surface", status: "production-ready", description: "水面与流体路径段。", builder: "water", supportsGrid: false, supportsBatching: true },
  { id: "primitive.free-polygon", status: "planned", description: "自由多边形可站立面。", builder: "planned:polygon", supportsGrid: true, supportsBatching: false },
  { id: "primitive.curved-wall", status: "prototype", description: "分段圆弧墙体。", builder: "roundWall", supportsGrid: false, supportsBatching: true },
  { id: "primitive.boolean-opening", status: "planned", description: "门窗、洞口和切割体。", builder: "planned:boolean-opening", supportsGrid: false, supportsBatching: false },
] as const satisfies readonly import("./schema").GeometryPrimitiveDefinition[];

export const SPATIAL_ATOMS: readonly SpatialAtomDefinition[] = [
  atom({ id: "terrain.height-field", status: "production-ready", category: "terrain", label: "分层高程场", description: "生成可站立面、坡面和真实垂直断面。", tags: ["terrain", "elevation", "cliff-face"], geometryBuilder: "renderMorphologyField" }),
  atom({ id: "terrain.irregular-clearing", status: "validated", category: "terrain", label: "不规则林间空地", description: "从生态覆盖中切出不规则战斗空间。", tags: ["clearing", "terrain", "standable"], geometryBuilder: "buildForestClearings" }),
  atom({ id: "terrain.crater-rim", status: "validated", category: "terrain", label: "破碎环坑", description: "有缺口、内坡和外缘喷出物的冲击坑。", tags: ["crater", "rim", "fracture"], geometryBuilder: "buildImpactCrater" }),
  atom({ id: "terrain.caldera", status: "validated", category: "terrain", label: "破火山口", description: "不完整环壁、熔岩底和多条危险出口。", tags: ["caldera", "volcanic", "lava"], geometryBuilder: "buildVolcanic" }),
  atom({ id: "water.meandering-channel", status: "production-ready", category: "water", label: "弯曲主河道", description: "连续流体路径形成主水道，宽度、曲率、水位和可渡点随分层 Seed 改变。", tags: ["river", "channel", "waterflow"], geometryBuilder: "buildRiverValleyContinuous", gridRule: "water-edge" }),
  atom({ id: "water.tributary", status: "validated", category: "water", label: "支流", description: "两条或多条分叉流线汇入主水道，改变岸线与渡点。", tags: ["tributary", "river", "waterflow"], geometryBuilder: "buildRiverTributary", gridRule: "water-edge" }),
  atom({ id: "water.waterfall", status: "validated", category: "water", label: "瀑布与跌水池", description: "流体沿台阶从高处跌落，上、下游水位不同并生成真实竖向水面。", tags: ["waterfall", "drop", "deep-pool"], geometryBuilder: "buildWaterfall", gridRule: "water-edge" }),
  atom({ id: "ecology.tree-cluster", status: "production-ready", category: "ecology", label: "树群", description: "按斑块而非均匀散点生成乔木和林冠。", tags: ["tree", "forest", "canopy", "cover"], geometryBuilder: "buildTreeCluster", lod: "instanced" }),
  atom({ id: "ecology.undergrowth", status: "validated", category: "ecology", label: "林下植被", description: "影响移动和视线的灌木、蕨类和枯枝。", tags: ["undergrowth", "forest", "difficult-terrain"], geometryBuilder: "buildUndergrowth", lod: "instanced" }),
  atom({ id: "ecology.fallen-log", status: "validated", category: "ecology", label: "倒木", description: "可攀爬、作掩体或桥接浅沟的倒木。", tags: ["fallen-log", "cover", "climbable"], geometryBuilder: "buildFallenLog" }),
  atom({ id: "ecology.ancient-tree", status: "validated", category: "ecology", label: "巨树战术点", description: "大型树干、根台和可达树冠平台。", tags: ["giant-tree", "canopy-platform", "high-ground"], geometryBuilder: "buildAncientTree" }),
  atom({ id: "route.surface-trail", status: "production-ready", category: "route", label: "贴地路径", description: "路径跟随可站立表面并连接战术区。", tags: ["route", "trail", "surface-grid"], geometryBuilder: "corridor" }),
  atom({ id: "route.bridge", status: "production-ready", category: "route", label: "桥梁", description: "跨越水、裂缝或高差的有支撑通道。", tags: ["bridge", "route", "supported"], geometryBuilder: "corridor" }),
  atom({ id: "route.vertical", status: "production-ready", category: "route", label: "垂直交通", description: "楼梯、坡道或梯子两端落在可站立面。", tags: ["vertical-route", "stairs", "support"], geometryBuilder: "stairConnection" }),
  atom({ id: "tactical.platform", status: "production-ready", category: "tactical", label: "战术平台", description: "有真实高度、入口与边缘防护的制高点。", tags: ["platform", "high-ground", "standable"], geometryBuilder: "buildTacticalPlatform" }),
  atom({ id: "structure.embedded-building", status: "production-ready", category: "structure", label: "场地内独立建筑", description: "以独立 Seed、地基和入口嵌入自然或聚落。", tags: ["building", "interior", "foundation", "entrance"], geometryBuilder: "instantiateBuildingModule", lod: "unique" }),
  atom({ id: "terrain.slope", status: "prototype", category: "terrain", label: "连续斜坡外观", description: "以可批处理楔形几何柔化相邻高程带，同时保持水平战术面为移动权威。", tags: ["slope-facade", "terrain", "erosion-facing"], geometryBuilder: "renderMorphologyField:ramp", validation: ["wedge-positive-volume", "facade-not-standable", "high-edge-faces-upper-band"], visualFixtures: ["forest-slope-low-angle", "dry-channel-slope-overview", "same-seed-replay"], failureConditions: ["slope-marked-standable-without-grid", "high-edge-points-downhill"] }),
  atom({ id: "terrain.erosion-skirt", status: "prototype", category: "terrain", label: "裸露地貌外缘裙边", description: "把荒地、冲沟与岩岸的外圈竖墙转为向地图外下降的合并坡岸；不适用于植被覆盖边界。", tags: ["erosion-skirt", "terrain", "non-walkable-facade"], geometryBuilder: "renderMorphologyField:edge-skirt", validation: ["high-edge-aligns-boundary", "skirt-not-standable", "domain-opt-in"], visualFixtures: ["dry-channel-skirt-aligned-overview", "dry-channel-skirt-aligned-low", "forest-skirt-rejection"], failureConditions: ["skirt-invades-grid-cell", "universal-border-ring"] }),
  atom({ id: "ecology.forest-edge-transition", status: "prototype", category: "ecology", label: "不连续林缘过渡", description: "以局部根台、灌丛与倒木簇打散森林外缘；保留视线缺口，不形成连续装饰环。", tags: ["forest", "forest-edge", "roots", "undergrowth", "fallen-log"], geometryBuilder: "buildForestEdgeTransition", validation: ["clusters-are-discontinuous", "roots-not-standable", "seed-sensitive"], visualFixtures: ["forest-edge-overview", "forest-edge-low", "forest-edge-seed-variant"], failureConditions: ["continuous-border-ring", "unsupported-floating-root", "entrance-completely-blocked"] }),
  atom({ id: "terrain.terrace", status: "planned", category: "terrain", label: "自然台地", description: "带断面和边缘破碎的多级可站立台地。", tags: ["terrace", "shelf", "high-ground"], geometryBuilder: "planned:terrace" }),
  atom({ id: "terrain.ravine", status: "validated", category: "terrain", label: "弯曲沟谷", description: "连续切开场地，生成双岸、深层裂谷底、真实断面、有限桥点和下降路线。", tags: ["ravine", "rift", "void", "cliff-face", "rift-bottom"], geometryBuilder: "buildRift", traversal: ["walk", "climb", "jump"], tacticalEffects: ["hazard", "chokepoint", "high-ground", "alternate-route"], validation: ["void-separates-banks", "rift-bottom-is-lower-than-banks", "bridge-ends-supported", "descent-reaches-bottom"], visualFixtures: ["rift-overview", "rift-low-angle", "rift-topology", "same-seed-replay", "different-seed-variation"], failureConditions: ["painted-line-on-intact-floor", "missing-vertical-faces", "bridge-floats", "bottom-unreachable"] }),
  atom({ id: "terrain.crevasse", status: "prototype", category: "terrain", label: "冰川裂缝", description: "用真正缺失的可站立面、深冰壁与有限桥点完全分开两侧冰川。", tags: ["ice", "crevasse", "void", "bridge"], geometryBuilder: "buildIce:main-crevasse", validation: ["banks-are-separated", "crossings-are-supported", "crevasse-bottom-is-not-standable"], visualFixtures: ["ice-crevasse-overview", "ice-crevasse-low", "ice-crevasse-top"], failureConditions: ["dark-line-painted-on-intact-floor", "bridge-floats", "route-crosses-void"] }),
  atom({ id: "terrain.cave-chamber", status: "prototype", category: "terrain", label: "洞穴与岩窟腔体", description: "已生成多腔体洞穴图、边界洞壁、通道侧壁、不同高程、岩架和危险区；天然侵蚀轮廓与连续洞顶仍需提高。", tags: ["cave", "cavern", "grotto", "岩窟", "溶洞", "chamber", "cave-wall", "ledge", "underground"], geometryBuilder: "buildCave", traversal: ["walk", "climb"], tacticalEffects: ["cover", "high-ground", "hazard", "chokepoint"], validation: ["chamber-graph-connected", "passages-touch-chambers", "multiple-elevation-bands", "hazard-does-not-block-all-routes"], visualFixtures: ["cave-overview", "cave-low-angle", "cave-chamber-graph", "same-seed-replay", "different-seed-variation"], failureConditions: ["rooms-without-cave-walls", "ring-palisade-instead-of-eroded-shell", "disconnected-chamber", "flat-single-floor", "passage-floats"] }),
  atom({ id: "terrain.floating-island", status: "prototype", category: "terrain", label: "有厚度浮岛与浮空岩盘", description: "已生成三档高度、破碎足迹、岛间深渊和真实垂直交通；低角度下岛体厚度、悬索桥护栏和升降构件仍需提高。", tags: ["floating-island", "浮空", "悬空", "浮岛", "vertical-face", "high-ground", "void"], geometryBuilder: "buildFloatingIslands", traversal: ["walk", "climb", "jump"], tacticalEffects: ["high-ground", "hazard", "chokepoint", "alternate-route"], validation: ["at-least-three-elevation-bands", "islands-have-undersides", "vertical-routes-connect-islands", "void-is-not-standable"], visualFixtures: ["floating-islands-overview", "floating-islands-low-angle", "floating-islands-levels", "same-seed-replay", "different-seed-variation"], failureConditions: ["coplanar-platform-stack", "thin-island-silhouette", "floating-without-underside", "route-crosses-empty-void", "unsupported-access"] }),
  atom({ id: "terrain.marsh-basin", status: "validated", category: "terrain", label: "沼泽盆地", description: "干地斑块、泥潭、水道和芦苇覆盖共同构成。", tags: ["swamp", "mud", "wetland", "boardwalk"], geometryBuilder: "buildSwamp", tacticalEffects: ["hazard", "chokepoint", "cover"], visualFixtures: ["swamp-overview", "swamp-boardwalk", "same-seed-replay"], failureConditions: ["flat-dry-field", "boardwalk-without-water"] }),
  atom({ id: "terrain.coastal-cliff", status: "planned", category: "terrain", label: "海岸崖线", description: "海面、崖壁、潮台与上下崖路线。", tags: ["coast", "cliff", "tide"], geometryBuilder: "planned:coastal-cliff" }),
  atom({ id: "water.pool", status: "planned", category: "water", label: "水池与深潭", description: "有岸缘、深浅区和可渡点的水体。", tags: ["pool", "water", "hazard"], geometryBuilder: "planned:pool" }),
  atom({ id: "water.tidal-channel", status: "planned", category: "water", label: "潮汐水道", description: "水位状态改变合法路线与站立面。", tags: ["tide", "channel", "state-change"], geometryBuilder: "planned:tidal-channel" }),
  atom({ id: "water.lava-network", status: "prototype", category: "water", label: "熔岩网络", description: "主熔岩池、支流和跨越点组成的危险网络。", tags: ["lava", "lava-branch", "hazard"], geometryBuilder: "buildVolcanic" }),
  atom({ id: "ecology.root-network", status: "validated", category: "ecology", label: "巨树根系", description: "以树干壳体为父空间生成根墙、根桥、根部档案洞和可攀爬根台。", tags: ["root", "giant-tree", "route", "root-archive", "root-bridge"], geometryBuilder: "addHollowTreeCity:root-network", traversal: ["walk", "climb"], tacticalEffects: ["cover", "high-ground", "chokepoint", "alternate-route"], validation: ["roots-connect-shell-to-ground", "root-archive-is-reachable", "root-routes-have-support"], visualFixtures: ["hollow-tree-root-overview", "root-archive-cutaway", "root-route-low-angle", "same-seed-replay"], failureConditions: ["decorative-roots-without-route", "root-archive-sealed", "floating-root"] }),
  atom({ id: "ecology.fungal-grove", status: "prototype", category: "ecology", label: "巨型菌林", description: "蘑菇伞台、菌柄掩体和孢子危险区。", tags: ["fungal", "mushroom", "platform"], geometryBuilder: "addGiantFungalLandmarks" }),
  atom({ id: "structure.room-cell", status: "validated", category: "structure", label: "功能房间", description: "把 BuildingProgram 房间图落实为独立楼板、边界墙、门洞、用途、净空和邻接关系。", tags: ["room", "wall", "door", "program-room", "room-partition"], geometryBuilder: "buildBuildingProgram:room-cell", lod: "unique", instancingStrategy: "none", tacticalEffects: ["cover", "chokepoint", "objective"], validation: ["room-has-floor-and-boundary", "adjacent-rooms-have-opening", "required-room-is-reachable", "room-volumes-do-not-overlap"], visualFixtures: ["building-floor-cutaway", "room-adjacency-top", "door-opening-detail", "same-seed-replay", "different-seed-variation"], failureConditions: ["metadata-room-without-walls", "sealed-required-room", "room-volume-overlap", "door-away-from-wall"] }),
  atom({ id: "structure.courtyard", status: "planned", category: "structure", label: "围合庭院", description: "由建筑体块围合而非独立地板声明的庭院。", tags: ["courtyard", "exterior", "enclosure"], geometryBuilder: "planned:courtyard" }),
  atom({ id: "structure.roof-system", status: "prototype", category: "structure", label: "屋顶系统", description: "坡屋顶、女儿墙和可达平台已有真实几何；部分机构建筑仍退化为完整矩形屋顶，破损穹顶与屋顶路线表现尚未统一。", tags: ["roof", "pitched-roof", "parapet", "roof-route", "roof-platform"], geometryBuilder: "buildBuildingProgram:roof-system", lod: "unique", instancingStrategy: "none", traversal: ["walk", "climb"], tacticalEffects: ["high-ground", "cover", "alternate-route"], validation: ["roof-matches-room-mass", "roof-platform-has-access", "parapet-does-not-block-entry", "roof-route-is-supported"], visualFixtures: ["roof-overview", "roof-low-angle", "roof-route-top", "same-seed-replay", "different-seed-variation"], failureConditions: ["single-flat-rectangle-for-all-masses", "roof-platform-unreachable", "roof-floats", "missing-parapet-at-high-platform"] }),
  atom({ id: "structure.spiral-stair", status: "prototype", category: "structure", label: "连续旋梯", description: "踏步连续旋转并连接真实楼层开口。", tags: ["spiral-stair", "vertical-route", "opening"], geometryBuilder: "buildSpiralStair" }),
  atom({ id: "structure.wall-opening", status: "prototype", category: "structure", label: "墙与开口", description: "门洞已由房间邻接真实切分墙段；窗口目前仍包含立面板方案，尚未达到完整窗台、过梁和洞口合同。", tags: ["wall", "door", "door-frame", "window", "opening"], geometryBuilder: "buildBuildingProgram:walls-and-door-openings", lod: "unique", instancingStrategy: "none", tacticalEffects: ["cover", "chokepoint"], validation: ["door-opening-lies-on-wall-boundary", "door-connects-valid-spaces", "wall-does-not-cross-room-interior"], visualFixtures: ["wall-opening-cutaway", "door-frame-detail", "window-prototype-exterior", "same-seed-replay"], failureConditions: ["solid-wall-across-connection", "floating-door-frame", "window-plate-without-wall-cut"] }),
  atom({ id: "structure.supported-catwalk", status: "planned", category: "structure", label: "有支撑猫道", description: "立柱、梁、护栏、入口与网格完整的高架通道。", tags: ["catwalk", "support", "guardrail"], geometryBuilder: "planned:supported-catwalk" }),
  atom({ id: "tactical.cover-cluster", status: "planned", category: "tactical", label: "掩体组合", description: "服务视线与路线的高低掩体组，而非随机散点。", tags: ["cover", "line-of-sight", "tactical"], geometryBuilder: "planned:cover-cluster" }),
  atom({ id: "state.collapse", status: "validated", category: "state", label: "坍塌状态", description: "从建筑中移除部分真实墙体，并生成瓦砾、缺口、危险区、临时桥和备用路线。", tags: ["collapse", "collapsed", "rubble", "temporary-bridge", "alternate-route"], geometryBuilder: "applyBuildingStates:collapse", lod: "unique", instancingStrategy: "none", traversal: ["walk", "climb", "jump"], tacticalEffects: ["cover", "hazard", "alternate-route"], validation: ["wall-count-decreases", "rubble-is-physical", "alternate-route-remains-valid", "required-rooms-remain-reachable"], visualFixtures: ["collapse-before-after", "collapse-route-cutaway", "collapse-low-angle", "same-seed-replay"], failureConditions: ["color-only-collapse", "all-routes-destroyed", "temporary-bridge-floats", "rubble-blocks-only-exit"] }),
  atom({ id: "state.flood", status: "validated", category: "state", label: "淹水状态", description: "在地下或低洼房间生成真实水面，并改变危险、可站立区域和调查路线。", tags: ["flood", "flooded", "water", "state-change", "hazard"], geometryBuilder: "applyBuildingStates:flood", lod: "unique", instancingStrategy: "none", traversal: ["walk", "swim"], tacticalEffects: ["hazard", "chokepoint", "alternate-route"], validation: ["water-is-inside-low-room", "water-level-is-above-floor", "vertical-access-remains-valid"], visualFixtures: ["flooded-basement-cutaway", "flood-water-level-low-angle", "flood-route-top", "same-seed-replay"], failureConditions: ["blue-color-without-water-geometry", "water-outside-room", "basement-completely-inaccessible"] }),
  atom({ id: "state.overgrowth", status: "prototype", category: "state", label: "植物侵入", description: "已有真实植被与根柱几何和掩体效果；尚未系统生成可验证的攀爬端口与备用路线。", tags: ["overgrowth", "overgrown", "root", "cover"], geometryBuilder: "applyBuildingStates:overgrowth", lod: "unique", instancingStrategy: "none", traversal: ["walk", "climb"], tacticalEffects: ["cover"], validation: ["vegetation-is-physical-geometry", "growth-does-not-seal-only-route"], visualFixtures: ["overgrowth-exterior", "overgrowth-cutaway", "overgrowth-route-prototype", "same-seed-replay"], failureConditions: ["green-tint-only", "growth-floats", "only-entrance-blocked"] }),
  atom({ id: "structure.hollow-tree-shell", status: "validated", category: "structure", label: "空心古树壳体", description: "由不规则树皮段、根部支撑和内部环带共同形成可进入的巨树城市容器。", tags: ["hollow-tree", "bark-wall", "spiral-tree-street", "root-archive"], geometryBuilder: "addHollowTreeCity", tacticalEffects: ["cover", "high-ground", "hazard"], visualFixtures: ["tree-shell-small", "tree-shell-large", "same-seed-replay", "different-seed-variation"], failureConditions: ["solid-trunk-blocks-interior", "unsupported-canopy"] }),
  atom({ id: "ecology.mangrove-canopy", status: "validated", category: "ecology", label: "红树林冠层与根网", description: "把潮汐水道、树根栈道、吊脚建筑和冠层掩体绑定到同一湿地支撑面。", tags: ["mangrove", "canopy", "prop-root", "root-boardwalk"], geometryBuilder: "addMangroveSmugglerPort", tacticalEffects: ["cover", "hazard", "chokepoint"], visualFixtures: ["mangrove-sparse", "mangrove-dense", "same-seed-replay", "different-seed-variation"], failureConditions: ["dry-flat-marsh", "floating-dock"] }),
  atom({ id: "terrain.salt-crystal-island", status: "validated", category: "terrain", label: "盐晶浮岛", description: "分离的盐晶承载面、暴露底面和高度端口组成可建造浮空层。", tags: ["salt-crystal", "floating-island", "vertical-face", "high-ground"], geometryBuilder: "addFloatingIslandTerrain", tacticalEffects: ["high-ground", "hazard", "chokepoint"], visualFixtures: ["salt-island-low-angle", "salt-island-top", "same-seed-replay", "different-seed-variation"], failureConditions: ["coplanar-platforms", "floating-without-underside"] }),
  atom({ id: "water.cavern-tide-pool", status: "validated", category: "water", label: "洞底潮池", description: "浮空建筑下方的深水参照面，提供潮池危险和垂直空间尺度。", tags: ["cavern-tide-pool", "watercourse", "hazard"], geometryBuilder: "addFloatingIslandTerrain", tacticalEffects: ["hazard", "alternate-route"], visualFixtures: ["tide-pool-overview", "tide-pool-low-angle", "same-seed-replay"], failureConditions: ["water-without-basin", "unreachable-pool"] }),
  atom({ id: "structure.monastery-cluster", status: "validated", category: "structure", label: "修道院群", description: "礼拜堂、居室、钟塔和服务建筑分别落在父地貌的承载端口上。", tags: ["monastery", "shrine", "tower", "building", "suspension-bridge"], geometryBuilder: "instantiateBuildingModule", tacticalEffects: ["high-ground", "chokepoint", "cover"], visualFixtures: ["monastery-cluster-overview", "monastery-cluster-low-angle", "same-seed-replay"], failureConditions: ["single-box-monastery", "unconnected-island-buildings"] }),
] as const;

export const CAPABILITY_CARDS: readonly CapabilityCard[] = SPATIAL_ATOMS.map((entry) => ({ id: entry.id, label: entry.label, description: entry.description, status: entry.status, tags: entry.tags, atomIds: [entry.id], environments: entry.tags.filter((tag) => ["forest", "river", "volcanic", "cave", "building", "swamp", "coast"].includes(tag)), inputPorts: entry.inputPorts.map((port) => port.kind), outputPorts: entry.outputPorts.map((port) => port.kind), constraints: entry.constraints, recommendedWith: [], qualityGrade: entry.status === "production-ready" ? "A" : entry.status === "validated" ? "B" : entry.status === "prototype" ? "C" : "planned" }));

export const FUNCTIONAL_MODULES: readonly FunctionalModule[] = [
  { id: "module.forest-stratum", label: "森林垂直生态层", capabilityIds: ["terrain.height-field", "ecology.tree-cluster", "ecology.undergrowth"], requiredPorts: ["surface"], realizedTags: ["forest", "canopy", "undergrowth", "elevation"] },
  { id: "module.forest-tactical", label: "森林战术路径", capabilityIds: ["terrain.irregular-clearing", "ecology.fallen-log", "ecology.ancient-tree", "route.surface-trail", "tactical.platform"], requiredPorts: ["route"], realizedTags: ["clearing", "fallen-log", "giant-tree", "canopy-platform"] },
  { id: "module.swamp-system", label: "沼泽水陆战术系统", capabilityIds: ["terrain.marsh-basin", "route.bridge", "structure.embedded-building"], requiredPorts: ["surface", "water", "route"], realizedTags: ["swamp", "water", "boardwalk", "hazard", "building"] },
  { id: "module.river-system", label: "完整河流系统", capabilityIds: ["terrain.height-field", "water.meandering-channel", "water.tributary", "water.waterfall", "route.bridge"], requiredPorts: ["water", "route"], realizedTags: ["river", "tributary", "waterfall", "deep-pool"] },
  { id: "module.volcanic-system", label: "火山构造系统", capabilityIds: ["terrain.height-field", "terrain.caldera", "route.surface-trail", "tactical.platform"], requiredPorts: ["surface", "route"], realizedTags: ["caldera", "lava", "fracture", "basalt-platform"] },
  { id: "module.crater-system", label: "冲击坑系统", capabilityIds: ["terrain.height-field", "terrain.crater-rim", "route.surface-trail", "tactical.platform"], requiredPorts: ["surface", "route"], realizedTags: ["impact-crater", "rim", "ejecta", "central-impact"] },
  { id: "module.rift-system", label: "裂谷双岸系统", capabilityIds: ["terrain.height-field", "terrain.ravine", "route.bridge", "route.vertical", "tactical.platform"], requiredPorts: ["surface", "route", "vertical"], realizedTags: ["rift", "crevasse", "rift-bottom", "bridge", "cliff-descent"] },
  { id: "module.cave-network", label: "多腔体洞穴网络", capabilityIds: ["terrain.cave-chamber", "route.surface-trail", "route.vertical", "tactical.platform"], requiredPorts: ["route", "vertical"], realizedTags: ["cave", "chamber", "passage", "ledge", "hazard"] },
  { id: "module.floating-stack", label: "有厚度浮岛垂直栈", capabilityIds: ["terrain.floating-island", "route.bridge", "route.vertical", "tactical.platform"], requiredPorts: ["support", "route", "vertical"], realizedTags: ["floating-island", "vertical-face", "void", "high-ground"] },
  { id: "module.site-building", label: "自然场地建筑", capabilityIds: ["structure.embedded-building", "route.surface-trail"], requiredPorts: ["route", "support"], realizedTags: ["building", "interior", "foundation", "site-access"] },
  { id: "module.cavern-monastery", label: "洞穴修道院复合体", capabilityIds: ["terrain.cave-chamber", "water.cavern-tide-pool", "structure.monastery-cluster", "route.vertical"], requiredPorts: ["support", "water", "route", "vertical"], realizedTags: ["cave", "salt-crystal", "cavern-tide-pool", "building", "vertical-route"] },
  { id: "module.parent-terrain-compound", label: "承载地貌复合场所", capabilityIds: ["structure.hollow-tree-shell", "ecology.mangrove-canopy", "terrain.salt-crystal-island", "water.cavern-tide-pool", "structure.monastery-cluster", "route.vertical"], requiredPorts: ["support", "route", "vertical"], realizedTags: ["hollow-tree", "mangrove", "salt-crystal", "cavern-tide-pool", "building", "vertical-route"] },
] as const;

export const DESIGNER_MOTIFS: readonly DesignerMotif[] = [
  { id: "motif.closed-canopy-clearings", label: "封闭林冠与三空地", domain: "forest", moduleIds: ["module.forest-stratum", "module.forest-tactical"], requiredCapabilities: ["ecology.tree-cluster", "terrain.irregular-clearing"], structuralRules: ["clearings-are-irregular", "trails-connect-clearings", "canopy-platform-is-reachable"], identityChecks: ["canopy-coverage-visible", "at-least-two-elevation-bands"] },
  { id: "motif.wetland-boardwalk-station", label: "泥潭斑块、栈道与湿地站点", domain: "swamp", moduleIds: ["module.swamp-system", "module.site-building"], requiredCapabilities: ["terrain.marsh-basin", "route.bridge", "structure.embedded-building"], structuralRules: ["water-divides-dry-ground", "boardwalk-connects-dry-islands", "station-foundation-is-supported"], identityChecks: ["wetland-readable-without-title", "boardwalk-crosses-water"] },
  { id: "motif.waterfall-valley", label: "有落差的支流河谷", domain: "river", moduleIds: ["module.river-system"], requiredCapabilities: ["water.meandering-channel", "water.tributary", "water.waterfall"], structuralRules: ["water-level-monotonic", "tributaries-join-main-channel", "two-legal-crossings"], identityChecks: ["vertical-water-face-visible", "banks-form-valley"] },
  { id: "motif.water-city-quays", label: "主河与不规则沿岸水城", domain: "river", moduleIds: ["module.river-system", "module.site-building"], requiredCapabilities: ["water.meandering-channel", "water.tributary", "route.bridge", "structure.embedded-building"], structuralRules: ["main-canal-divides-districts", "tributaries-create-waterfront-frontage", "quays-follow-water-edge", "buildings-stay-on-buildable-banks"], identityChecks: ["water-city-readable-without-title", "market-dock-is-waterfront", "crossings-have-different-hierarchy"] },
  { id: "motif.broken-caldera", label: "破碎多支流火山口", domain: "volcanic", moduleIds: ["module.volcanic-system"], requiredCapabilities: ["terrain.caldera", "tactical.platform"], structuralRules: ["rim-has-gaps", "lava-has-branches", "safe-route-crosses-hazard"], identityChecks: ["caldera-readable-without-title", "basalt-high-ground-visible"] },
  { id: "motif.impact-basin", label: "喷出物与裂缝冲击坑", domain: "crater", moduleIds: ["module.crater-system"], requiredCapabilities: ["terrain.crater-rim", "tactical.platform"], structuralRules: ["rim-broken", "descent-route-reaches-floor", "fractures-radiate"], identityChecks: ["central-impact-visible", "rim-not-campfire"] },
  { id: "motif.rift-two-banks", label: "双岸与深层裂谷底", domain: "rift", status: "validated", moduleIds: ["module.rift-system"], requiredCapabilities: ["terrain.height-field", "route.bridge", "route.vertical"], structuralRules: ["void-separates-banks", "two-crossings", "bottom-is-reachable"], identityChecks: ["both-banks-visible", "vertical-faces-visible", "bridge-ends-supported"] },
  { id: "motif.connected-cavern-graph", label: "多高程洞穴腔体图", domain: "cave", status: "validated", moduleIds: ["module.cave-network"], requiredCapabilities: ["terrain.cave-chamber", "route.surface-trail"], structuralRules: ["chambers-form-connected-graph", "at-least-one-loop", "ledge-is-reachable"], identityChecks: ["cave-readable-without-title", "multiple-elevation-bands", "passages-touch-chambers"] },
  { id: "motif.three-tier-floating-stack", label: "三档有厚度浮岛", domain: "floating", status: "validated", moduleIds: ["module.floating-stack"], requiredCapabilities: ["terrain.floating-island", "route.vertical"], structuralRules: ["three-height-bands", "void-separates-islands", "vertical-routes-connect-levels"], identityChecks: ["undersides-visible", "islands-not-coplanar", "access-is-supported"] },
  { id: "motif.eroded-ice-ridges", label: "侵蚀冰盖、非对称雪脊与融水裂缝", domain: "ice", status: "validated", moduleIds: [], requiredCapabilities: ["terrain.height-field"], structuralRules: ["ice-edge-is-broken", "ridges-have-windward-and-leeward-profiles", "thaw-pools-interrupt-routes", "density-changes-meso-counts"], identityChecks: ["ice-field-readable-without-title", "ridge-cross-section-visible", "no-single-rectangular-ice-slab"] },
  { id: "motif.embedded-building", label: "地貌内独立建筑", domain: "mixed-site", moduleIds: ["module.site-building"], requiredCapabilities: ["structure.embedded-building"], structuralRules: ["foundation-touches-terrain", "entrance-connects-site-route"], identityChecks: ["building-has-interior", "no-floating-access"] },
  { id: "motif.hollow-tree-city", label: "空心古树内部城市", domain: "forest", moduleIds: ["module.parent-terrain-compound"], requiredCapabilities: ["structure.hollow-tree-shell", "structure.embedded-building"], structuralRules: ["bark-encloses-cavity", "spiral-route-connects-levels", "root-archive-is-accessible"], identityChecks: ["tree-shell-visible", "city-inside-tree"] },
  { id: "motif.mangrove-smuggler-port", label: "红树林走私港", domain: "forest", moduleIds: ["module.parent-terrain-compound"], requiredCapabilities: ["ecology.mangrove-canopy", "water.tidal-channel", "structure.embedded-building"], structuralRules: ["tide-channel-divides-site", "boardwalks-follow-roots", "underwater-entry-is-reachable"], identityChecks: ["mangrove-silhouette-visible", "dock-is-not-flat-road"] },
  { id: "motif.salt-crystal-cavern-monastery", label: "潮汐盐晶洞穴修道院", domain: "cave", status: "validated", moduleIds: ["module.cavern-monastery"], requiredCapabilities: ["terrain.cave-chamber", "water.cavern-tide-pool", "structure.monastery-cluster"], structuralRules: ["cavern-parent-remains-visible", "monastery-buildings-use-cave-shelves", "tidal-pool-is-below-main-route", "vertical-route-reaches-bell-tower"], identityChecks: ["salt-crystals-visible", "cave-boundary-visible", "monastery-is-not-a-single-box"] },
  { id: "motif.salt-crystal-monastery", label: "盐晶浮空修道院群", domain: "generic", moduleIds: ["module.parent-terrain-compound"], requiredCapabilities: ["terrain.salt-crystal-island", "structure.monastery-cluster", "water.cavern-tide-pool"], structuralRules: ["three-island-height-bands", "bridges-connect-islands", "cavern-pool-below"], identityChecks: ["salt-crystals-visible", "vertical-scale-visible"] },
] as const;

export const COMPOSITION_GRAMMARS: readonly CompositionGrammar[] = [
  { id: "grammar.forest-v1", label: "森林生态—战术语法", domain: "forest", allowedMotifs: ["motif.closed-canopy-clearings", "motif.embedded-building"], orderingRules: ["macro-terrain", "clearings", "routes", "ecology", "tactical", "micro"], topologyChecks: ["all-clearings-reachable", "platform-reachable"] },
  { id: "grammar.swamp-v1", label: "沼泽水陆与架高交通语法", domain: "swamp", allowedMotifs: ["motif.wetland-boardwalk-station", "motif.embedded-building"], orderingRules: ["wetland-basin", "dry-islands", "water-pools", "raised-boardwalks", "supported-buildings", "hazards", "micro"], topologyChecks: ["dry-islands-reachable", "boardwalk-supported", "building-foundation-grounded"] },
  { id: "grammar.river-v1", label: "河谷水文语法", domain: "river", allowedMotifs: ["motif.waterfall-valley", "motif.embedded-building"], orderingRules: ["macro-valley", "water-network", "crossings", "ecology", "micro"], topologyChecks: ["downhill-flow", "both-banks-reachable"] },
  { id: "grammar.water-city-v1", label: "水城沿岸规划语法", domain: "river", allowedMotifs: ["motif.water-city-quays", "motif.embedded-building"], orderingRules: ["main-canal", "district-splits", "irregular-bank-routes", "crossings", "quays-and-market", "independent-buildings", "micro"], topologyChecks: ["main-watercourse-continuous", "branches-join-main", "both-banks-reachable", "buildings-on-banks"] },
  { id: "grammar.volcanic-v1", label: "火山危险场语法", domain: "volcanic", allowedMotifs: ["motif.broken-caldera"], orderingRules: ["macro-caldera", "lava-network", "safe-shelves", "routes", "micro"], topologyChecks: ["objective-reachable", "hazard-not-total-block"] },
  { id: "grammar.crater-v1", label: "冲击坑语法", domain: "crater", allowedMotifs: ["motif.impact-basin"], orderingRules: ["macro-rim", "fractures", "descent", "ejecta", "micro"], topologyChecks: ["floor-reachable", "rim-route-exists"] },
  { id: "grammar.crevasse-v1", label: "裂谷与冰隙语法", domain: "rift", status: "validated", allowedMotifs: ["motif.rift-two-banks", "motif.embedded-building"], orderingRules: ["macro-fracture", "banks", "bottom", "crossings", "vertical-routes", "micro"], topologyChecks: ["banks-separated", "crossings-supported", "bottom-route-valid"] },
  { id: "grammar.ice-field-v1", label: "冰盖侵蚀、雪脊与冻融语法", domain: "ice", status: "validated", allowedMotifs: ["motif.eroded-ice-ridges", "motif.embedded-building"], orderingRules: ["eroded-base-plates", "asymmetric-ridges", "thaw-pools", "crevasses", "routes", "micro"], topologyChecks: ["base-plates-form-readable-field", "ridge-routes-supported", "hazards-do-not-remove-all-crossings"] },
  { id: "grammar.cave-network-v1", label: "洞穴腔体图语法", domain: "cave", status: "validated", allowedMotifs: ["motif.connected-cavern-graph", "motif.salt-crystal-cavern-monastery"], orderingRules: ["chambers", "passages", "vertical-ledges", "hazards", "micro"], topologyChecks: ["chamber-graph-connected", "loop-exists", "ledge-route-supported"] },
  { id: "grammar.floating-stack-v1", label: "浮岛垂直栈语法", domain: "floating", status: "validated", allowedMotifs: ["motif.three-tier-floating-stack", "motif.embedded-building"], orderingRules: ["lower-island", "middle-island", "upper-island", "undersides", "vertical-routes", "micro"], topologyChecks: ["three-height-bands", "void-not-standable", "all-islands-reachable"] },
  { id: "grammar.generic-v1", label: "保守组合语法", domain: "generic", allowedMotifs: [], orderingRules: ["macro", "routes", "tactical", "micro"], topologyChecks: ["primary-route-exists"] },
] as const;

export function capabilityById(id: string): CapabilityCard | undefined { return CAPABILITY_CARDS.find((entry) => entry.id === id); }
export function motifById(id: string): DesignerMotif | undefined { return DESIGNER_MOTIFS.find((entry) => entry.id === id); }

export interface AtomQualityResult { atomId: string; ready: boolean; issues: string[]; }
export function auditAtomQuality(entry: SpatialAtomDefinition): AtomQualityResult {
  const issues: string[] = [];
  if (entry.footprintCells.min.some((value) => value <= 0) || entry.footprintCells.max.some((value, index) => value < entry.footprintCells.min[index]!)) issues.push("invalid-footprint-range");
  if (entry.elevationFeet.max < entry.elevationFeet.min) issues.push("invalid-elevation-range");
  if (!entry.geometryBuilder) issues.push("missing-geometry-builder");
  if (entry.validation.length < 2) issues.push("insufficient-automatic-validation");
  if (entry.visualFixtures.length < 3) issues.push("insufficient-visual-fixtures");
  if (entry.failureConditions.length < 2) issues.push("insufficient-failure-conditions");
  if ((entry.status === "validated" || entry.status === "production-ready") && entry.geometryBuilder.startsWith("planned:")) issues.push("ready-status-without-builder");
  return { atomId: entry.id, ready: issues.length === 0 && (entry.status === "validated" || entry.status === "production-ready"), issues };
}

export function catalogMaturity(): Record<CapabilityStatus, number> {
  return SPATIAL_ATOMS.reduce<Record<CapabilityStatus, number>>((counts, entry) => { counts[entry.status] += 1; return counts; }, { planned: 0, prototype: 0, validated: 0, "production-ready": 0 });
}
